sudo: false
language: bash
os:
  - linux
install:
  - npm i -g npm
  - npm install -g csslint
  - npm --version
  - csslint --version
script:
  - csslint --format=compact $TRAVIS_BUILD_DIR/github-markdown.css